﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Collections;
using System.Threading.Tasks;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace GeoTouch
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIColourLoversApi : IColourLoversApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIColourLoversApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<List<ColourLovers.ServiceModel.Colors>> GetRandomColour()
        {
            var arguments = new object[] {  };
            return (Task<List<ColourLovers.ServiceModel.Colors>>) methodImpls["GetRandomColour"](Client, arguments);
        }

        public virtual Task<List<ColourLovers.ServiceModel.Patterns>> GetRandomPattern()
        {
            var arguments = new object[] {  };
            return (Task<List<ColourLovers.ServiceModel.Patterns>>) methodImpls["GetRandomPattern"](Client, arguments);
        }

    }
}


